services:
  myapi:
    build:
      context: .
      network: host
    ports:
      - "8000:8000"
    environment:
      - API_TOKEN=${API_TOKEN}
    volumes:
      - ./app/data:/home/noboobs/n/app/data
      - /home/noboobs/noBS_BotIntegrator/src:/home/noboobs/n/app/data/images

