name: Docker Deployment

on:
  workflow_run:
    workflows: [Docker Image CI]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    env:
      AZURE_SSH_KEY: ${{ secrets.AZURE_SSH_KEY }}
      AZURE_SSH_USER: ${{ secrets.AZURE_SSH_USER }}
      AZURE_SSH_IP: ${{ secrets.AZURE_SSH_IP }}
    steps:
    - uses: actions/checkout@v4
    - name: Create ssh file
      run : |
        echo $AZURE_SSH_KEY > ./azure_key.pem
        chmod 600 ./azure_key.pem
    - name: Pull and deploy docker on Azure
      run : |
          ssh -tt -o StrictHostKeyChecking=no -i ./azure_key.pem $AZURE_SSH_USER@$AZURE_SSH_IP << 'EOF'
            cd ./noboobs/noBS_AccountAPI
            
            git fetch --all
            git reset --hard origin/main
            git clean -fd -e app/data
            
            docker pull ghcr.io/sl0wyx/nobs_serverapi:latest
            docker compose -e "./app/data/private/.env" up -d --build
          EOF
